on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  CI:
    uses: Josdasim/pipelines-templates/.github/workflows/ci-python-tests.yml@main
    with:
      python-version: "3.12.3"
      run-lint: true
      run-tests: true
